// Real browser acceptance against disposable fixtures; see docs/TESTING.md.
import assert from 'node:assert/strict'
import fs from 'node:fs'
const {chromium}=await import(process.env.PLAYWRIGHT_MODULE||'playwright')
const fixture=JSON.parse(fs.readFileSync('work/confirmation-browser-fixture.json'))
const origin=process.env.CONFIRMATION_ORIGIN||'http://127.0.0.1:5373'
const browser=await chromium.launch({channel:'chrome',headless:true})
const page=await browser.newPage({viewport:{width:1440,height:900}})
const errors=[],logs=[];let checks=0
page.on('pageerror',e=>errors.push(String(e)));page.on('console',m=>logs.push({type:m.type(),text:m.text()}))
const check=(v,msg)=>{assert(v,msg);console.log('PASS',++checks,msg)}
const idle=()=>page.waitForSelector('.confirmation-page[data-busy="false"]')
const session=async(sid=fixture.main.sid)=>{const r=await page.request.get(`${origin}/api/confirmation/sessions/${sid}`,{headers:{Authorization:`Bearer ${fixture.token}`}});assert.equal(r.status(),200);return r.json()}
const changes=async(sid=fixture.main.sid)=>{const r=await page.request.get(`${origin}/api/confirmation/sessions/${sid}/changes`,{headers:{Authorization:`Bearer ${fixture.token}`}});assert.equal(r.status(),200);return (await r.json()).items}
const final=async(id)=>{const r=await page.request.get(`${origin}/api/final-versions/${id}`,{headers:{Authorization:`Bearer ${fixture.token}`}});assert.equal(r.status(),200);return r.json()}
const blur=()=>page.locator('.confirmation-flow').click({position:{x:310,y:12}})
const button=(name)=>page.getByRole('button',{name,exact:true})
const choose=async(c)=>{await page.getByTestId('choose-'+c.toLowerCase()).click();await idle()}
const go=async(n)=>{await page.getByRole('textbox',{name:'修改项序号'}).fill(String(n));await button('前往').click();await idle()}
const open=async(sid)=>{await idle();await page.locator(`[data-session-id="${sid}"]`).click();await idle();if(await page.getByRole('button',{name:'留在上次位置'}).count())await button('留在上次位置').click()}
try{
 await page.addInitScript(({token})=>{localStorage.setItem('rare-sperm-token',token);localStorage.setItem('rare-sperm-auth',JSON.stringify({id:'3',name:'confirm-C',role:'annotator'}))},fixture)
 await page.goto(origin+'/confirm');await open(fixture.main.sid)
 check((await session()).progress.decided===0,'browsing does not make decisions')
 await button('领取并开始确认').click();await idle()
 check((await session()).confirmerId===3,'claim persists assignment without decision')
 const pair=page.locator('.c-crops svg')
 check(await pair.count()===2,'A/B paired crops use actual frame image')
 const box1=await pair.nth(0).getAttribute('viewBox'),box2=await pair.nth(1).getAttribute('viewBox')
 check(box1===box2,'paired crops have identical source coordinates')
 const full=await page.locator('[data-variant="full"]').getAttribute('viewBox')
 check(full==='0 0 800 450','full context uses original video dimensions')
 await button('叠加对比').click();check(await page.locator('.c-crops svg').getAttribute('viewBox')===box1,'overlay uses the same crop')
 await page.getByRole('slider',{name:'局部缩放'}).fill('8');check(await page.locator('.c-crops svg').getAttribute('viewBox')!==box1,'zoom changes detail crop')
 check(await page.locator('[data-variant="full"]').getAttribute('viewBox')===full,'zoom keeps full-frame context stable')
 await button('A / B 并排').click();await page.getByRole('slider').fill('5')
 await page.evaluate(()=>scrollTo(0,0));await page.screenshot({path:'output/playwright/confirmation-initial.png',fullPage:true})
 await page.getByRole('textbox',{name:'搜索视频'}).fill('a');await page.keyboard.press('a')
 check((await session()).progress.decided===0,'typing A in input does not select')
 await page.getByRole('textbox',{name:'搜索视频'}).fill('');await blur();await page.keyboard.press('Control+a')
 check((await session()).progress.decided===0,'Ctrl+A is isolated from A choice')
 await button('快捷键 ?').click();await page.keyboard.press('b')
 check((await session()).progress.decided===0,'dialog isolates decision shortcuts')
 await page.keyboard.press('Shift+Tab');check(await button('关闭').evaluate(e=>document.activeElement===e),'dialog traps focus')
 await page.keyboard.press('Escape')
 await page.evaluate(()=>{window.dispatchEvent(new KeyboardEvent('keydown',{key:'b',repeat:true}));window.dispatchEvent(new KeyboardEvent('keydown',{key:'a',isComposing:true}))})
 check((await session()).progress.decided===0,'held keys and IME composition do not select')
 await blur();await page.keyboard.press('b');await idle()
 check((await session()).progress.decided===1,'B shortcut saves immediately')
 check((await page.getByTestId('current-item').innerText()).includes('对象 #2'),'auto-next advances to next pending item')
 await blur();await page.keyboard.press('Meta+z');await idle()
 check((await session()).progress.decided===0,'Cmd+Z restores pending choice')
 check((await page.getByTestId('current-item').innerText()).includes('对象 #1'),'undo returns to affected item')
 await page.getByRole('checkbox').uncheck();await choose('B')
 check((await page.getByTestId('current-item').innerText()).includes('修改项 1 / 3'),'auto-next off keeps selection')
 const rev=(await changes())[0].decisionRevision;await choose('B');check((await changes())[0].decisionRevision===rev,'same choice does not create extra decision')
 await page.reload();await idle();if(await button('留在上次位置').count())await button('留在上次位置').click()
 check((await page.getByTestId('current-item').innerText()).includes('修改项 1 / 3'),'resume restores server bookmark')
 check(await page.getByRole('checkbox').isChecked()===false,'display preference persists')
 await page.getByRole('button',{name:/撤销上一次选择/}).click();await idle()
 check((await session()).progress.decided===0,'undo remains available after refresh')
 await choose('A');await choose('B');await page.getByRole('button',{name:/撤销上一次选择/}).click();await idle()
 check((await changes())[0].decision.choice==='A','undo choice revision restores previous A')
 await choose('B');await blur();await page.keyboard.press('ArrowRight');await idle();await choose('A')
 await go(3);await choose('B');await page.getByRole('dialog').waitFor()
 check((await session()).state==='in_progress','last choice does not auto-finalize video')
 await page.keyboard.press('a');check((await changes())[2].decision.choice==='B','completion dialog isolates keyboard')
 await button('继续检查').click();check(await page.getByTestId('complete-video').isEnabled(),'all choices enable explicit completion')
 await page.getByTestId('complete-video').click();await button('确认完成').click();await idle()
 const firstVersion=(await session()).finalVersionId,firstFinal=await final(firstVersion)
 check((await session()).state==='confirmed'&&firstVersion,'explicit completion creates final version')
 check(await page.getByTestId('choose-a').isDisabled(),'completed video is readonly')
 const [download]=await Promise.all([page.waitForEvent('download'),button('导出完整视频 JSON').click()]);await idle()
 const json=JSON.parse(fs.readFileSync(await download.path()))
 check(json.frames.length===4&&json.frames[3].objects.length===0,'download contains complete video and empty frame')
 check(json.frames[0].objects[0].bbox[0]===207.125&&json.frames[0].objects[0].bbox[2]===269.625,'fractional coordinates survive final export')
 check(json.frames[0].objects[1].classKey==='debris'&&json.frames[0].objects[1].choice==='A','class and A selection survive export')
 check(json.frames[2].objects[0].resolution==='unchanged','unmodified frames retain A')
 await go(1);await page.setViewportSize({width:1366,height:768});await page.evaluate(()=>scrollTo(0,0));await page.screenshot({path:'output/playwright/confirmation-completed-1366.png',fullPage:true})
 check(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),'1366px layout has no horizontal page overflow')
 await button('重新确认').click();await button('开始重新确认').click();await idle()
 check((await session()).state==='in_progress'&&(await session()).progress.decided===3,'reopen keeps choices and enables editing')
 await go(3);await choose('A');await button('确认完成').click();await idle()
 const secondVersion=(await session()).finalVersionId,secondFinal=await final(secondVersion)
 check(secondVersion!==firstVersion&&secondFinal.previousFinalVersionId===firstVersion,'reconfirmation creates linked new version')
 check(JSON.stringify(await final(firstVersion))===JSON.stringify(firstFinal),'prior final version remains immutable')
 await open(fixture.zero.sid);await button('领取并开始确认').click();await idle()
 check((await session(fixture.zero.sid)).permissions.canComplete,'zero-change video can explicitly finish')
 await page.getByTestId('complete-video').click();await button('确认完成').click();await idle()
 const zero=await final((await session(fixture.zero.sid)).finalVersionId)
 check(zero.frames.length===4&&zero.frames[0].objects[0].resolution==='unchanged','zero-change final includes all original frames')
 check(errors.length===0,'no uncaught browser errors')
 console.log(`SUCCESS ${checks} checks`)
}finally{
 fs.mkdirSync('output/playwright',{recursive:true});fs.writeFileSync('output/playwright/confirmation-browser-console.json',JSON.stringify({errors,logs},null,2));await page.screenshot({path:'output/playwright/confirmation-last.png',fullPage:true});await browser.close()
}
