from pathlib import Path
p=Path('frontend/src/pages/ResultsPage.vue');s=p.read_text().replace("import { computed, onMounted, ref } from 'vue'", "import { computed, onMounted, ref, watch } from 'vue'\nimport AppIcon from '../components/AppIcon.vue'")
s=s.replace("const selectedMediaId = ref('')", "const selectedMediaId = ref('')\nconst search = ref(''), page = ref(1)\nconst pageSize = 50")
s=s.replace("`${row.media_type || 'video'}:${String(row.media_name || row.media_id).trim().toLocaleLowerCase()}`", "`${row.media_type || 'video'}:${row.media_id}`")
s=s.replace('    // 同一文件（兼容历史临时 media_id）、同一帧、同一标注人只显示一行。', '    // Use stable media identity: distinct videos may legitimately share a filename.')
s=s.replace('      continue\n    }\n    groups.set(key', "      if (row.created_at > existing.savedAt) existing.savedAt = row.created_at\n      continue\n    }\n    groups.set(key")
s=s.replace('  return Array.from(groups.values())', "  const term = search.value.toLowerCase()\n  return Array.from(groups.values()).filter(row => `${row.mediaName} ${row.username} ${row.objects.join(' ')}`.toLowerCase().includes(term))")
s=s.replace("    errorMessage.value = error?.message || '读取数据库标注记录失败'", "    errorMessage.value = error?.message || '读取数据库标注记录失败'\n    console.error('[records.load_failed]', error)")
s=s.replace('onMounted(load)', "const pageCount = computed(() => Math.max(1, Math.ceil(groupedRows.value.length / pageSize)))\nconst visibleRows = computed(() => groupedRows.value.slice((page.value-1)*pageSize,page.value*pageSize))\nwatch([search,selectedMediaId],()=>{page.value=1})\nwatch(pageCount,n=>{page.value=Math.min(page.value,n)})\nonMounted(load)")
s=s[:s.index('<template>')]+'''<template>
  <section class="records-page">
    <header class="records-heading"><div><span class="eyebrow">ANNOTATION RECORDS</span><h2>标注记录</h2><p>回查已入库的人工对象与标注人；最终数据集在对比确认完成后导出。</p></div><button class="btn-secondary" :disabled="loading" @click="load">{{ loading?'读取中…':'刷新记录' }}</button></header>
    <div class="records-stats"><div><AppIcon name="folder"/><span>素材<strong>{{ mediaOptions.length }}</strong></span></div><div><AppIcon name="list"/><span>当前筛选<strong>{{ groupedRows.length }} <small>条帧记录</small></strong></span></div><p>独立查询入口，无需经过此页即可送审。</p></div>
    <div class="panel records-panel"><div class="records-filters"><input v-model="search" class="input" aria-label="搜索标注记录" placeholder="搜索素材、对象或标注人…"/><select v-model="selectedMediaId" class="input" aria-label="按素材筛选"><option value="">全部素材</option><option v-for="media in mediaOptions" :key="media.id" :value="media.id">{{ media.name }} · {{ media.id.slice(-8) }}</option></select><span>按素材 / 帧 / 标注人汇总</span></div>
    <div v-if="errorMessage" class="error-banner" role="alert">{{ errorMessage }}</div>
    <div class="records-table"><table><thead><tr><th>素材</th><th>帧号</th><th>人工标注对象</th><th>标注人</th><th>最近入库时间</th></tr></thead><tbody><tr v-for="row in visibleRows" :key="row.key"><td><strong>{{ row.mediaName }}</strong><small>{{ row.mediaType==='video'?'视频':'图片' }} · {{ row.mediaId.slice(-10) }}</small></td><td>{{ row.frameIndex===null?'—':row.frameIndex+1 }}<small v-if="row.timestampMs!==null">{{ formatTimestamp(row.timestampMs) }}</small></td><td><div class="record-tags"><span v-for="name in row.objects" :key="name">{{ name }}</span><span v-if="!row.objects.length">—</span></div></td><td>{{ row.username }}</td><td>{{ formatSavedAt(row.savedAt) }}</td></tr><tr v-if="!visibleRows.length"><td colspan="5" class="records-empty">{{ loading?'正在读取记录…':search||selectedMediaId?'没有匹配的记录':'暂无已入库的人工标注记录' }}</td></tr></tbody></table></div>
    <footer class="records-pagination"><small>第 {{ page }} / {{ pageCount }} 页 · 每页 {{ pageSize }} 条</small><button class="btn-secondary" :disabled="page===1" @click="page--">上一页</button><button class="btn-secondary" :disabled="page===pageCount" @click="page++">下一页</button></footer></div>
  </section>
</template>
<style scoped>
.records-page{max-width:1600px;margin:10px auto;display:flex;flex-direction:column;gap:22px}.records-heading{display:flex;align-items:center;justify-content:space-between}.records-heading h2{font-size:24px;font-weight:650;margin-top:5px}.records-heading p{font-size:12px;color:var(--muted);margin-top:8px}.records-stats{display:flex;gap:16px;align-items:center}.records-stats>div{display:flex;gap:14px;align-items:center;padding:18px 24px;background:var(--surface);border:1px solid var(--line);border-radius:10px;min-width:180px;color:var(--accent)}.records-stats span{font-size:10px;color:var(--muted)}.records-stats strong{display:block;color:var(--text);font-size:24px;font-weight:600}.records-stats strong small{font-size:11px;color:var(--muted);font-weight:400}.records-stats p{margin-left:auto;color:var(--muted);font-size:11px}.records-panel{overflow:hidden}.records-filters{display:flex;gap:12px;padding:17px;border-bottom:1px solid var(--line);align-items:center}.records-filters input{width:300px}.records-filters select{max-width:260px}.records-filters span{margin-left:auto;font-size:11px;color:var(--muted)}.records-table{overflow:auto;max-height:calc(100vh - 360px);min-height:220px}table{width:100%;font-size:12px;border-collapse:collapse}th{position:sticky;top:0;background:var(--surface-subtle);color:var(--muted);text-align:left;font-weight:500}th,td{padding:15px 20px;border-bottom:1px solid var(--line)}td{vertical-align:top}td strong{font-weight:550}td small{display:block;color:var(--muted);font-size:10px;margin-top:5px}tbody tr:hover{background:var(--surface-subtle)}.record-tags{display:flex;gap:6px;flex-wrap:wrap;max-width:400px}.record-tags span{background:var(--accent-soft);color:var(--accent);border-radius:5px;padding:3px 7px;font-size:11px}.records-empty{text-align:center;padding:70px;color:var(--muted)}.records-pagination{display:flex;gap:8px;align-items:center;padding:13px 17px}.records-pagination small{margin-right:auto;color:var(--muted);font-size:11px}
</style>
'''
p.write_text(s)
p=Path('frontend/src/pages/ReviewPage.vue');s=p.read_text();a=s.index('    <div class="review-flow">');b=s.index('</div>',a)+6;s=s[:a]+'''    <div class="review-flow"><strong>审查模式</strong><span>逐帧检查 · 修改后提交本帧</span><small>A 原始标注永久保留</small></div>'''+s[b:];p.write_text(s)
p=Path('frontend/src/pages/ConfirmationPage.vue');s=p.read_text();a=s.index('    <nav class="confirmation-flow"');b=s.index('</nav>',a)+6;s=s[:a]+'''    <nav class="confirmation-flow" aria-label="当前阶段"><strong>对比确认</strong><span>逐项选择 A / B · 完成后导出训练集</span><small>原始版本永久保留</small><button @click="modal='help'">快捷键 ?</button></nav>'''+s[b:];p.write_text(s)
p=Path('frontend/src/review/review.css');s=p.read_text()
for a,b in {'#1548a5':'var(--accent)','#367cff':'var(--accent)','#111e33':'var(--surface-subtle)','#448dff':'var(--accent)','#122b50':'var(--accent-soft)','#8abaff':'var(--accent)','#153460':'var(--accent-soft)','#3e321b':'var(--warning-soft)','#ecc26c':'var(--warning)','#133d31':'var(--success-soft)','#69d4a5':'var(--success)','#27364d':'var(--line)','#26344c':'var(--line)','#367eff':'var(--accent)','#acc0db':'var(--muted)','#edc77b':'var(--warning)','#9db0ca':'var(--muted)'}.items():s=s.replace(a,b)
s+='\n.review-flow{height:40px;padding:0 3px}.review-flow strong{font-size:18px;letter-spacing:-.02em;color:var(--text)}.review-flow>span{font-size:11px}.panel-r{border-radius:10px;box-shadow:var(--shadow)}.review-page button{border-radius:6px}.review-top{gap:12px}.review-page .primary{background:var(--accent);color:white}.review-modal{background:var(--surface)}\n'
p.write_text(s)
p=Path('frontend/src/confirmation/confirmation.css');s=p.read_text();s+='\n.confirmation-flow{min-height:40px;padding:0 3px}.confirmation-flow strong{font-size:18px;letter-spacing:-.02em;color:var(--text)}.confirmation-flow>span{font-size:11px}.c-panel{border-radius:10px;box-shadow:var(--shadow)}.confirmation-sidebar{top:88px}.confirmation-image{--a:#c2a5ff;--b:#5fe1b0}.c-modal{background:var(--surface)}.c-stats{padding:7px 0}.confirmation-page .c-primary{color:white}.confirmation-layout{gap:12px}.confirmation-page button{border-radius:6px}\n';p.write_text(s)
# Login uses the same surfaces and theme store even before the authenticated shell mounts.
p=Path('frontend/src/pages/LoginPage.vue');s=p.read_text().replace("import { useAuth } from '../stores/auth'", "import { useAuth } from '../stores/auth'\nimport { useAppearance } from '../stores/appearance'\nimport AppIcon from '../components/AppIcon.vue'\nconst { theme, toggleTheme } = useAppearance()")
s=s.replace('class="min-h-screen bg-slate-950 px-5 text-slate-100"','class="login-page min-h-screen px-5"').replace('class="panel w-full p-8"','class="panel w-full p-8 login-card"').replace('>RS</div>','><AppIcon name="layers" :size="25" /></div>')
s=s.replace('text-slate-500','text-[var(--muted)]').replace('text-slate-400','text-[var(--muted)]').replace('text-indigo-300','text-[var(--accent)]').replace('border-slate-800 bg-slate-950/70','border-[var(--line)] bg-[var(--surface-subtle)]')
s=s.replace('<div class="mx-auto flex min-h-screen', '<button class="quiet-button login-theme" @click="toggleTheme"><AppIcon :name="theme===\'light\'?\'moon\':\'sun\'"/>{{ theme===\'light\'?\'深色模式\':\'浅色模式\' }}</button>\n    <div class="mx-auto flex min-h-screen')
s+='\n<style scoped>\n.login-page{background:radial-gradient(ellipse at 25% 15%,var(--accent-soft),transparent 60%),var(--app-bg);color:var(--text)}.login-card{box-shadow:0 22px 80px #243c5718;border-radius:18px}.login-theme{position:absolute;right:24px;top:24px}\n</style>\n'
p.write_text(s)
